---

name: release-pipeline
on:
  push:
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Install golang
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23

      # Checkout to the latest commit
      # On specific directory/path
      - name: Checkout
        uses: actions/checkout@v2

      - name: Building toxiproxy
        run: |
          make prod-build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
